package edu.sabanciuniv.berry.controller;


import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import edu.sabanciuniv.berry.domain.Authority;
import edu.sabanciuniv.berry.domain.Note;
import edu.sabanciuniv.berry.domain.User;
import edu.sabanciuniv.berry.repository.AuthorityRepository;
import edu.sabanciuniv.berry.repository.NoteByUsernameRepository;
import edu.sabanciuniv.berry.repository.NoteRepository;
import edu.sabanciuniv.berry.repository.SearchNoteRepository;
import edu.sabanciuniv.berry.repository.UserRepository;



@Controller
public class HomeController {
	
	public User currentUser = new User();
	
	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	private AuthorityRepository authorityRepository;
	
	@Autowired
	private NoteRepository noteRepository;
	
	
	@Autowired
	private NoteByUsernameRepository notebyUsernameRepository;
	
	@Autowired
	private SearchNoteRepository searchNoteRepository;

	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String welcome(ModelMap model) {
		// This returns a JSON or XML with the users
		
		model.addAttribute("userList", userRepository.findAll());
				
		return "welcome";
	}
	

	// Login form
	@RequestMapping(value = "/login", method = RequestMethod.POST)
	public String login() {
		if (SecurityContextHolder.getContext().getAuthentication() != null
				&& SecurityContextHolder.getContext().getAuthentication().isAuthenticated()
				&& !(SecurityContextHolder.getContext().getAuthentication() instanceof AnonymousAuthenticationToken)) {
				// user has already logged in
			return "redirect:/";
		} else {		
			return "login";
		}
	}
	
	@RequestMapping(value = "/login", method = RequestMethod.GET)
	public String login(@Valid User user, BindingResult result, HttpServletRequest request,Model model) {
		if (result.hasErrors()) 
		{
			return "login";
		
		} else {
			Optional<User> check = userRepository.findById(user.getUsername());
			if(check.isPresent()==true) 
			{
				if (check.get().getUsername().equals(user.getUsername()) && check.get().getPassword().equals(user.getPassword()))
				{
					currentUser.setUsername(check.get().getUsername().toString()); 
					currentUser.setFirstName(check.get().getFirstName().toString());
					currentUser.setLastName(check.get().getLastName().toString());
					currentUser.setSchoolID(check.get().getSchoolID());
					return "redirect:/index";
				}
				else
				{
					model.addAttribute("logError","logError");
					return "login";
				} 
			}
			else 
			{ 
				model.addAttribute("logError","logError");
				return "login";
			}
		}	
	}

	
	// Login form
	@RequestMapping(value = "/register", method = RequestMethod.GET)
	public String register(ModelMap model) {
		if (SecurityContextHolder.getContext().getAuthentication() != null
				&& SecurityContextHolder.getContext().getAuthentication().isAuthenticated()
				&& !(SecurityContextHolder.getContext().getAuthentication() instanceof AnonymousAuthenticationToken)) {
			// user has already logged in
			return "redirect:/";
		} else {
			// to make available for binding, we need default user
			model.addAttribute("user", new User());
			return "register";
		}
	}

	@RequestMapping(value = "/register", method = RequestMethod.POST)
	public String register(@Valid User user, BindingResult result, HttpServletRequest request) {

		if (result.hasErrors()) {
			return "register";
		} else {
			Optional<User> check = userRepository.findById(user.getUsername());
			if (check.isPresent() == false) {
				userRepository.save(user);

				Authority auth = new Authority();
				auth.setUsername(user.getUsername());
				auth.setRole("ROLE_USER");
				authorityRepository.save(auth);
				return "login";
			} else { // it means that this username exists
				return "redirect:/register?error";
			}
		}	
	}
	
	@RequestMapping(value = "/index", method = RequestMethod.GET)
	public String index(ModelMap model) {
		
		
		model.addAttribute("noteList", noteRepository.findAll());		
		
		return "index";
	}
	
	
	@RequestMapping(value = "/addnote", method = RequestMethod.GET)
	public String addnote(ModelMap model) {
		
		model.addAttribute("note", new Note());
		return "addnote";
	}
	
	@RequestMapping(value = "/addnote", method = RequestMethod.POST)
	public String addnote(@Valid Note note, BindingResult result, HttpServletRequest request) {
		
		if (result.hasErrors()) 
		{
			return "addnote";
		
		}else
		{
				//Hangi kullanıcı ekledi
				note.setUserID(currentUser.getUsername());
				noteRepository.save(note);
		}	
		
		return "redirect:/index";
	}
	
	@RequestMapping("/profile")
	public String profile(Model md) {
		
		Optional<User> test=userRepository.findById(currentUser.getUsername());
		md.addAttribute("user", test);
		
		
		
		md.addAttribute("noteList", notebyUsernameRepository.findTitleById(currentUser.getUsername()));
		
		return "profile";
	}
	
	@RequestMapping(value = "/guest", method = RequestMethod.GET)
	public String guest(ModelMap model) {
		
		model.addAttribute("noteList", noteRepository.findAll());		
		
		return "guest";
	}
	
	@RequestMapping(value = "/settings", method = RequestMethod.POST)
	public String settings(@Valid User user, BindingResult result, HttpServletRequest request) {
		
		if (result.hasErrors()) 
		{
			return "settings";
		
		} else
		{		
			userRepository.save(user);
		}	
		
		return "redirect:/login";
	}
	
	@RequestMapping(value = "/settings", method = RequestMethod.GET)
	public String settings(Model model) {
		
		Optional<User> test=userRepository.findById(currentUser.getUsername());
		model.addAttribute("user", test);
		return "settings";
	}	
	
    
	@RequestMapping(value="/search", method = RequestMethod.POST)
    public String search(@RequestParam(value="courseName") String courseName, Model model)
    {
		List<Note> notes = new ArrayList<Note>();
		
		if(courseName=="") {
			
			Iterable<Note> u = noteRepository.findAll();
	        Iterator uIterator = u.iterator();

	        while (uIterator.hasNext())
	        {
	            notes.add((Note)uIterator.next());
	        }
			
			
		}else {

        

			Iterable<Note> u = searchNoteRepository.findByCourseIDContaining(courseName);
			Iterator uIterator = u.iterator();

			while (uIterator.hasNext())
			{
				notes.add((Note)uIterator.next());
			}
			
		}
        model.addAttribute("noteList", notes);
        model.addAttribute("notesCount", notes.size());
        model.addAttribute("notehStr", courseName);
        
        return "index";
    }
	
	@RequestMapping(value="/guestSearch", method = RequestMethod.POST)
    public String guestsearch(@RequestParam(value="courseid") String courseID, Model model)
    {
		List<Note> notes = new ArrayList<Note>();
		
		if(courseID=="") {
			
			Iterable<Note> u = noteRepository.findAll();
	        Iterator uIterator = u.iterator();

	        while (uIterator.hasNext())
	        {
	            notes.add((Note)uIterator.next());
	        }
			
			
		}else {

        

			Iterable<Note> u = searchNoteRepository.findByCourseIDContaining(courseID);
			Iterator uIterator = u.iterator();

			while (uIterator.hasNext())
			{
				notes.add((Note)uIterator.next());
			}
			
		}
        model.addAttribute("noteList", notes);
        model.addAttribute("notesCount", notes.size());
        model.addAttribute("notehStr", courseID);
        
        return "guest";
    }

}
